apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitopsapp
spec:
  selector:
    matchLabels:
      app: gitopsapp
  template:
    metadata:
      labels:
        app: gitopsapp
    spec:
      containers:
        - name: gitopsapp
          image: 'ghcr.io/hgaiji/gitopsapp:0.0.2'
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
